name: SuperItemsShop
main: Biswajit\SuperItems\SuperItemsShop
version: 2.0.0
api: 5.0.0
author: Biswajit
softdepend: ["BedrockEconomy", "EconomyAPI"]

commands:
  sshop:
    description: "use to open SuperItemsShop"
    usage: "/sshop"
    permission: sshop.cmd.use
permissions:
  sshop.cmd.use:
    description: "Permission To Use /sshop Command"
    default: true
