name: SuperItemsShop
main: Biswajit\SuperItems\SuperItemsShop
version: 2.0.0
api: 5.0.0
author: Biswajit

commands:
  sshop:
    description: "use to open SuperItemsShop"
    usage: "/sshop"
    permission: sshop.cmd
permissions:
  sshop.cmd:
    description: "Permission To Use /sshop Command"
    default: true
